function save_log(log, frame_idx, run_dir)
% SAVE_LOG  Write pipeline log as .mat and .csv into run_dir.
%
%   save_log(log, frame_idx, run_dir)

% .mat for reloading into MATLAB
save(fullfile(run_dir, 'pipeline_log.mat'), 'log');
fprintf('Log saved to %s\n', fullfile(run_dir, 'pipeline_log.mat'));

% Human-readable CSV
log_table = table( ...
    (1:frame_idx)',                     ...
    log.current_state,                  ...
    log.frame_energy_scalar,            ...
    log.onset_threshold,                ...
    log.confidence,                     ...
    log.path_x,                         ...
    log.path_y,                         ...
    log.detection_max,                  ...
    log.detection_mean,                 ...
    double(log.background_ready),       ...
    double(log.noise_floor_ready),      ...
    double(log.tracking_active),        ...
    double(log.processing_active),      ...
    log.state_duration,                 ...
    log.path_len,                       ...
    log.ax, log.bx, log.cx,            ...
    log.ay, log.by, log.cy,            ...
    log.t_ref,                          ...
    log.debug_centroid_x,               ...
    log.debug_centroid_y,               ...
    log.debug_n_detections,             ...
    log.debug_mode,                     ...
    log.debug_merged,                   ...
    log.debug_rejected,                 ...
    log.debug_change_max,               ...
    log.debug_pca_elongation,           ...
    log.debug_accum_count,              ...
    'VariableNames', {                  ...
        'frame',                        ...
        'state',                        ...
        'frame_energy',                 ...
        'onset_threshold',              ...
        'confidence',                   ...
        'path_x',                       ...
        'path_y',                       ...
        'detection_max',                ...
        'detection_mean',               ...
        'background_ready',             ...
        'noise_floor_ready',            ...
        'tracking_active',              ...
        'processing_active',            ...
        'state_duration',               ...
        'path_len',                     ...
        'ax', 'bx', 'cx',              ...
        'ay', 'by', 'cy',              ...
        't_ref',                        ...
        'centroid_x',                   ...
        'centroid_y',                   ...
        'n_detections',                 ...
        'det_mode',                     ...
        'centroid_merged',              ...
        'centroid_rejected',            ...
        'change_max',                   ...
        'pca_elongation',               ...
        'accum_count'                   ...
    });
writetable(log_table, fullfile(run_dir, 'pipeline_log.csv'));
fprintf('CSV saved to %s\n', fullfile(run_dir, 'pipeline_log.csv'));

end
